version: '3'
services:
  openrefine_app:
    restart: always
    build:
      context: .
      dockerfile: ./services/openrefine_apps/Dockerfile
    ports:
      - 4444:3333
    volumes:
        - ./openrefine-app/data:/data
    networks:
      - openrefine
  nginx: 
    image: nginx
    container_name: production_nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80
      - 443:443
    networks:
      - openrefine
    depends_on:
      - openrefine_app 
networks:
  openrefine: 
    driver: bridge