version: '3'
services:
  openrefine_app:
    container_name: openrefine_app
    restart: always
    image: asia.gcr.io/dev-medchek-pipeline/openrefine_app:3.0 
    ports:
      - 3333:3333
    volumes:
        - ./openrefine-app/data:/data
    networks:
      - openrefine
networks:
  openrefine: 
    driver: bridge