version: '3'
services:
  openrefine_app:
    container_name: openrefine_app
    restart: always
    build: 
      context: .
      dockerfile: ./services/openrefine_app/Dockerfile
    ports:
      - 3333:3333
    volumes:
        - ./openrefine-app/data:/data
    networks:
      - openrefine
networks:
  openrefine: 
    driver: bridge